language: cpp
script:
  - |
    for TOOL in gcc clang make ninja;
    do
      echo "---------------------------------------------------------------------"
      [ -f $(type -p $TOOL &>/dev/null) ] && $TOOL --version || echo "$TOOL: not found";
    done
