language: cpp
script:
  - |
    for TOOL in gcc clang make ninja cmake;
    do
      echo "---------------------------------------------------------------------"
      echo "Looking for $TOOL in $PATH: $(type -p $TOOL 2>/dev/null)"
      [ -f $(type -p $TOOL 2>/dev/null) ] && $TOOL --version || echo "$TOOL: not found";
      grep $(type -p $TOOL 2>/dev/null) /var/lib/dpkg/info/*.list;
    done
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - libclang-3.6-dev
    - llvm-3.6
    - llvm-3.6-dev
    - g++-4.9
    - g++-5
    - cmake
    - ninja-build
    - libgl1-mesa-dev
    - libegl1-mesa-dev
