language: cpp
script:
  - |
    for TOOL in g++-4.9 clang-3.7 make ninja cmake;
    do
      echo "---------------------------------------------------------------------"
      echo "Looking for $TOOL in $PATH: $(type -p $TOOL 2>/dev/null)"
      [ -f $(type -p $TOOL 2>/dev/null) ] && $TOOL --version || echo "$TOOL: not found";
      grep $(type -p $TOOL 2>/dev/null) /var/lib/dpkg/info/*.list;
    done
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - llvm-3.7
    - llvm-3.7-dev
    - g++-4.9
    - gcc-4.9
    - cmake
    - ninja-build
    - libgl1-mesa-dev
    - libegl1-mesa-dev
