language: objective-c
script:
  - |
    for TOOL in gcc clang make ninja cmake;
    do
      echo "---------------------------------------------------------------------"
      [ -f $(type -p $TOOL &>/dev/null) ] && $TOOL --version || echo "$TOOL: not found";
    done
before_install:
  - brew update
  - brew upgrade
  - brew list
  - brew tap homebrew/versions
  - brew install ninja
  - brew install cmake
  # - brew install gcc48 --enable-cxx
  # - brew install llvm34  --with-libcxx --with-clang --with-asan
