language: objective-c
script:
  - |
    for TOOL in gcc clang make ninja cmake;
    do
      echo "---------------------------------------------------------------------"
      [ -f $(type -p $TOOL &>/dev/null) ] && $TOOL --version || echo "$TOOL: not found";
    done
before_install:
  - sudo apt-get -qq install ninja-build
